server:
  port: 8090

smartHome:
  mqtt:
    server:
      address: localhost
      port: 1883
    devices:
      sensor:
        room: bedroom
        topic: "nodemcu_sensor/measurements"
      lightsActuator:
        room: bedroom
        topic: "nodemcu_actuator/lights"
      heaterActuator:
        room: bedroom
        topic: "nodemcu_actuator/heat"

spring:
  application:
    name: smarthome-backend
  jpa:
    generate-ddl: true
#    hibernate.hbm-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: example
  security:
    user:
      name: admin
      password: admin